name: Auto Commit Bot

on:
  schedule:
    - cron: "0 1 * * *"   # Jam 08 pagi WIB
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update activity log
        run: |
          echo "Run at $(date '+%Y-%m-%d %H:%M:%S')" >> activity.log

      - name: Commit changes
        run: |
          git config --global user.name "Suaib777"
          git config --global user.email "suaibmabayo77@gmail.com"

          git add .
          git commit -m "chore: daily auto update $(date '+%Y-%m-%d')"

      - name: Push changes
        run: |
          git push
